/** PMX Catalogue – Go Live: the 34 digital solutions (scrolling ticker on the home page). */
export const PMX_SOLUTION_NAMES = [
  'Project Command Centre',
  'PPMS Suite',
  'EPMS Project Risk',
  'EPMS Permitting',
  'Project Lesson Learn',
  'Benchmark Hub',
  'MYICONS',
  'P6 EPPM',
  'Smart Planner',
  'Aspen K-Base',
  'ORION',
  'SAFRAN',
  'Schedule Intelligent Dashboard',
  'Synchro 4D',
  'Project AI',
  'P-EDMS',
  'E-CDBM',
  'PTQ Online',
  'Selektor',
  'P-ELSOR',
  'FnGMap',
  'Augmented Engineering Review',
  'Engineering Maturity Index',
  'LNGPro',
  'ProTrackS',
  'CR Pro',
  'Advanced Work Packaging',
  'Construct Hub',
  'Project Production Management',
  'PCMS',
  'Quality+',
  'Online Project Quality',
  'Quality Card',
  'QPRS',
] as const
